# Generated by Django 3.1.1 on 2020-09-27 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='list',
            old_name='complated',
            new_name='completed',
        ),
    ]
